name: native_resource
description: Retrieve resource values stored in the native side of an iOS or Android App.
version: 0.1.0
homepage: https://github.com/ened/flutter_plugin_native_resource/

environment:
  sdk: '>=2.13.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: asia.ivity.flutter.native_resource
        pluginClass: NativeResourcePlugin
      ios:
        pluginClass: NativeResourcePlugin